## 6 Important things you should know about Numpy and Pandas
1. The data manipulation capabilities of pandas are built on top of the numpy library. In a way, numpy is a dependency of the pandas library.
2. Pandas is best at handling tabular data sets comprising different variable types (integer, float, double, etc.). In addition, the pandas library can also be used to perform even the most naive of tasks such as loading data or doing feature engineering on time series data.
3. Numpy is most suitable for performing basic numerical computations such as mean, median, range, etc. Alongside, it also supports the creation of multi-dimensional arrays.
4. Numpy library can also be used to integrate C/C++ and Fortran code.
5. Remember, python is a zero indexing language unlike R where indexing starts at one.
6. The best part of learning pandas and numpy is the strong active community support you'll get from around the world.

In [1]:
import numpy as np

### Create a list comprising numbers from 0 to 9

In [2]:
L = list(range(10))

### Converting integers to string:
This style of handling lists is known as list comprehension.

List comprehension offers a versatile way to handle list manipulations tasks easily. Here's an example.

In [3]:
[str(c) for c in L]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [4]:
[type(item) for item in L]

[int, int, int, int, int, int, int, int, int, int]

### Creating Arrays
Numpy arrays are homogeneous in nature, i.e., they comprise one data type (integer, float, double, etc.) unlike lists.

In [5]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Creating a 3 row x 5 column matrix

In [6]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Creating a matrix with a predefined value

In [7]:
np.full((3,5),1.23)

array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

### Create an array with a set sequence

In [8]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Create an array of even space between the given range of values

In [9]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### Create a 3x3 array with mean 0 and standard deviation 1 in a given dimension

In [10]:
np.random.normal(0, 1, (3,3))

array([[-0.00857098,  1.30632091, -0.23799731],
       [ 1.28367139, -1.53530111, -1.25203843],
       [-0.71986402, -0.19535371, -0.26843862]])

### Create an identity matrix

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.seed(0)


x1 = np.random.randint(10, size=6) #one dimension
x2 = np.random.randint(10, size=(3,4)) #two dimension
x3 = np.random.randint(10, size=(3,4,5)) #three dimension

print("x1 ndim:", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)

print("x2 ndim:", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x1 ndim: 1
x1 shape: (6,)
x1 size:  6
x2 ndim: 2
x2 shape: (3, 4)
x2 size:  12
x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size:  60


## Array Indexing
The important thing to remember is that indexing in python starts at zero.

In [13]:
x1 = np.array([4, 3, 4, 4, 8, 4])
x1

array([4, 3, 4, 4, 8, 4])

### Assess value to index zero

In [14]:
x1[0]

4

### Assess fifth value

In [15]:
x1[4]

8

### Get the last value

In [16]:
x1[-1]

4

### Get the second last value

In [17]:
x1[-2]

8

### In a multidimensional array, we need to specify row and column index

In [18]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

### 1st row and 2nd column value

In [19]:
x2[2,3]

7

### 3rd row and last value from the 3rd column

In [20]:
x2[2,-1]

7

### Replace value at 0,0 index

In [21]:
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Array Slicing
Now, we'll learn to access multiple or a range of elements from an array.

In [22]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### From start to 4th position

In [23]:
x[:5]


array([0, 1, 2, 3, 4])

### From 4th position to end

In [24]:
x[4:]

array([4, 5, 6, 7, 8, 9])

### From 4th to 6th position

In [25]:
x[4:7]

array([4, 5, 6])

### Return elements at even place

In [26]:
x[ : : 2]

array([0, 2, 4, 6, 8])

### Return elements from first position step by two


In [27]:
x[1::2]

array([1, 3, 5, 7, 9])

### Reverse the array

In [28]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Array Concatenation
Many a time, we are required to combine different arrays. So, instead of typing each of their elements manually, you can use array concatenation to handle such tasks easily.

### You can concatenate two or more arrays at once.

In [29]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [21,21,21]
np.concatenate([x, y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

### You can also use this function to create 2-dimensional arrays.

In [35]:
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

### Using its axis parameter, you can define row-wise or column-wise matrix

In [36]:
np.concatenate([grid,grid],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

### Concatenation of 2 different dimensions:2D and 1D

In [32]:
grid1 = np.array([3,4,5])
grid2 = np.array([[1,2,3],[17,18,19]])
np.vstack([grid1,grid2])

array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])

### Add an array using np.hstack

In [33]:
z = np.array([[9],[9]])
np.hstack([grid,z])

array([[1, 2, 3, 9],
       [4, 5, 6, 9]])

In [40]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
x1,x2,x3 = np.split(x,[3,6])
print(x1,x2,x3)


[0 1 2] [3 4 5] [6 7 8 9]


In [49]:
grid = np.arange(16).reshape((4,4))
grid
upper,lower = np.vsplit(grid,[2])
print (upper, lower)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]
